version: '3.8'
services:
  db:
    image: postgres:17
    env_file: .env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    command: gunicorn loan_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env.example
    depends_on:
      - db
      - redis
volumes:
  postgres_data: