# Generated by Django 5.2.4 on 2025-07-07 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration to create the LoanApplication model.

    This migration defines the 'LoanApplication' model with fields:
    - 'id': BigAutoField primary key.
    - 'amount': DecimalField(max_digits=10, decimal_places=2).
    - 'status': CharField with choices PENDING, APPROVED, REJECTED, FLAGGED, WITHDRAWN. Default 'PENDING'.
    - 'created_at': DateTimeField(auto_now_add=True).
    - 'updated_at': DateTimeField(auto_now=True).
    - 'user': ForeignKey to AUTH_USER_MODEL with CASCADE deletion.
    The model options include ordering by 'id'.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
