# Generated by Django 5.2.4 on 2025-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add the 'purpose' field to the LoanApplication model.

    This migration adds:
    - 'purpose': CharField(max_length=255), blank=True, default='', with help_text "Purpose for applying for the loan".
    """

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Purpose for applying for the loan",
                max_length=255,
            ),
        ),
    ]
