# Generated by Django 5.2.4 on 2025-07-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_flags",
                        to="loan.loanapplication",
                    ),
                ),
            ],
        ),
    ]
